# Generated by Django 5.2.17 on 2026-08-21 18:17

import applications.services.documents
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=32, unique=True)),
                ('exam_type', models.CharField(choices=[('cabin_crew', 'Cabin Crew'), ('ame', 'AME'), ('pilot', 'Pilot'), ('flight_dispatch', 'Flight Dispatch')], db_index=True, max_length=32)),
                ('detected_exam_type', models.CharField(blank=True, max_length=32)),
                ('detected_exam_type_evidence', models.CharField(blank=True, max_length=255)),
                ('detected_exam_type_ambiguous', models.BooleanField(default=False)),
                ('receipt_number', models.CharField(blank=True, db_index=True, max_length=64)),
                ('receipt_number_confidence', models.FloatField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('processing_status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued for OCR'), ('processing', 'OCR in progress'), ('failed', 'OCR failed'), ('mismatch', 'Examination type mismatch'), ('review', 'Awaiting verification'), ('confirmed', 'Confirmed'), ('scheduled', 'Scheduled')], db_index=True, default='draft', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('letter', 'Application Letter'), ('receipt', 'Payment Receipt')], max_length=16)),
                ('file', models.FileField(storage=applications.services.documents.PrivateDocumentStorage(), upload_to=applications.services.documents.document_upload_path)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('raw_text', models.TextField(blank=True)),
                ('mean_confidence', models.FloatField(blank=True, null=True)),
                ('engine', models.CharField(blank=True, max_length=64)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('used_text_layer', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
            ],
            options={
                'verbose_name': 'Application Document',
                'verbose_name_plural': 'Application Documents',
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('raw_name', models.CharField(max_length=255)),
                ('corrected_name', models.CharField(blank=True, max_length=255)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('is_included', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_candidates', to='applications.application')),
                ('possible_duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exams.examschedule')),
            ],
            options={
                'verbose_name': 'Extracted Candidate',
                'verbose_name_plural': 'Extracted Candidates',
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['-created_at'], name='application_created_b96b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['processing_status', '-created_at'], name='application_process_b09ba0_idx'),
        ),
        migrations.AddConstraint(
            model_name='applicationdocument',
            constraint=models.UniqueConstraint(fields=('application', 'kind'), name='unique_document_kind_per_application'),
        ),
        migrations.AddConstraint(
            model_name='extractedcandidate',
            constraint=models.UniqueConstraint(fields=('application', 'position'), name='unique_candidate_position'),
        ),
    ]
