# Generated by Django 5.2.17 on 2026-08-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='rotation_applied',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='skew_applied',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
