# Generated by Django 5.2.17 on 2026-08-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Signed in'), ('app_started', 'Application processing started'), ('doc_uploaded', 'Document uploaded'), ('ocr_done', 'OCR completed'), ('ocr_failed', 'OCR failed'), ('ocr_edited', 'OCR result corrected'), ('type_mismatch', 'Examination type mismatch'), ('confirmed', 'Application confirmed'), ('exam_id', 'Examination ID generated'), ('scheduled', 'Examination scheduled'), ('paper_sched', 'Examination paper scheduled'), ('slip', 'Examination slip generated')], max_length=32),
        ),
    ]
