# Generated by Django 5.2.14 on 2026-06-01 20:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(db_index=True, max_length=255)),
                ('exam_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('receipt_number', models.CharField(db_index=True, max_length=50)),
                ('company_name', models.CharField(db_index=True, max_length=255)),
                ('exam_type', models.CharField(choices=[('cabin_crew', 'Cabin Crew'), ('ame', 'AME'), ('pilot', 'Pilot'), ('flight_dispatch', 'Flight Dispatch')], db_index=True, max_length=32)),
                ('exam_date', models.DateField(db_index=True)),
                ('exam_time', models.TimeField()),
                ('venue', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='passports/%Y/%m/')),
                ('slip_token', models.CharField(blank=True, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Schedule',
                'verbose_name_plural': 'Exam Schedules',
                'ordering': ['-exam_date', '-exam_time'],
                'indexes': [models.Index(fields=['exam_date', 'exam_type'], name='exams_exams_exam_da_3d9242_idx'), models.Index(fields=['-created_at'], name='exams_exams_created_fdd3ef_idx')],
            },
        ),
    ]
