# Generated by Django 5.2.17 on 2026-08-21 18:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paper', models.CharField(choices=[('paper_1', 'Paper 1'), ('paper_2', 'Paper 2')], max_length=16)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Examination Paper',
                'verbose_name_plural': 'Examination Papers',
                'ordering': ['paper'],
            },
        ),
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=32)),
                ('year', models.PositiveIntegerField()),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Number Sequence',
                'verbose_name_plural': 'Number Sequences',
            },
        ),
        migrations.AddField(
            model_name='examschedule',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_records', to='applications.application'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='status',
            field=models.CharField(choices=[('pending_schedule', 'Awaiting scheduling'), ('scheduled', 'Scheduled')], db_index=True, default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='exam_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='exam_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='venue',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['status'], name='exams_exams_status_1d6b8b_idx'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='exams.examschedule'),
        ),
        migrations.AddConstraint(
            model_name='numbersequence',
            constraint=models.UniqueConstraint(fields=('scope', 'year'), name='unique_sequence_scope_year'),
        ),
        migrations.AddIndex(
            model_name='exampaper',
            index=models.Index(fields=['exam_date'], name='exams_examp_exam_da_1b75f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='exampaper',
            constraint=models.UniqueConstraint(fields=('exam', 'paper'), name='unique_paper_per_exam'),
        ),
    ]
